name: Build
on: [push]

jobs:
  build:
    name: Build pug and SCSS
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
      - run: |
          npm i
          npx gulp scss
          npx gulp pug
          npm run format

      - name: Archive index.html
        uses: actions/upload-pages-artifact@v1
        with:
          name: upload index.html
          path: index.html

      - name: Archive index.css
        uses: actions/upload-pages-artifact@v1
        with:
          name: upload index.css
          path: style/index.css

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy github pages
        id: deployment
        uses: actions/deploy-pages@v1


